Create MyRedBlackSet.h
rumazius/urban-couscous pull request #1
Opened 2022-02-23 15:11 UTC by rumazius

Петляк Максим Игоревич, длинный контест 4, задача А.
https://official.contest.yandex.ru/contest/34590/run-report/64579860/

2022-03-29 13:17 UTC, DimasKovas requested changes
В целом все ок

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +        size_t size_ = 0;
Почему тут _?
Обычно либо все private поля с _, либо все без

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +            Node() : left(nullptr), right(nullptr), parent(nullptr), key(0), red(false) {
Пустая строка между конструкторами/методами.

Давай зададим дефолтные значения при объявлении (nullptr/false), а в конструкторов оставим только те инициализации, которые отличаются key(key), parent(parent) и тд

key я бы явно не инициализировал. Тем более нулем это делать некоректно, ValueType может быть не числом

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +        Node* end_iter = nullptr;
Сокращения лучше не использовать

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +                    Node* nxt = lower_bound(v->left, key);
Экономим 1 букву?)

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +        void UpdateCorners() {
Используй единый стиль для именования методов

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +        void RotateLeft(Node* v) {
Пустая строка между методами

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +    Set(const Set& oth) {
other

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +
А тут лишняя строка

2022-03-29 13:17 UTC, DimasKovas commented on MyRedBlackSet.h
> +        iterator PrevNode(iterator p) {
Не сокращай, и нейминг методов опять (должен быть один стиль на весь проект)

2022-03-30 16:16 UTC, merged

2022-03-30 16:17 UTC, rumazius commented
Так, я не знаю, куда я нажал, но, вроде, всё пофиксил и отправил.